version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nodeApp/
 
hooks:
  BeforeInstall:
    - location: scripts/echo.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/restart_pm2.sh
      timeout: 180
      runas: ubuntu
